# The base URL of the site; the only required configuration variable.
base_url = "mywebsite.com"
generate_rss = true
compile_sass = true

# The site title and description; used in feeds by default.
title = "WOS instructions for TOS"
description = "Instructions to use Web of Science (WOS) files with Tree of Science (TOS)."
highlight_code = true

# The site theme to use.
theme = "zola-clean-blog"

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Dave"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
